project_id = "skfaqjatbqrmfkojtqsz"

[functions.create-booking-payment]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-stripe-connect-link]
verify_jwt = false
