// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/_shared.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
var readEnv = (name) => {
  const denoValue = globalThis.Deno?.env?.get?.(name);
  return denoValue ?? (typeof process !== "undefined" ? process.env[name] : void 0);
};
var errorResult = (text) => ({
  content: [{ type: "text", text }],
  structuredContent: { error: text },
  isError: true
});
var textResult = (text, structuredContent) => ({
  content: [{ type: "text", text }],
  structuredContent
});
var clampLimit = (limit, fallback = 10, max = 25) => {
  if (!Number.isFinite(limit ?? NaN)) return fallback;
  return Math.max(1, Math.min(Math.floor(limit), max));
};
var supabaseForUser = (ctx) => {
  if (!ctx.isAuthenticated()) {
    return { error: errorResult("Authentication required. Connect with OAuth and sign in to SpotVault first.") };
  }
  const token = ctx.getToken();
  const url = readEnv("SUPABASE_URL");
  const key = readEnv("SUPABASE_PUBLISHABLE_KEY") ?? readEnv("SUPABASE_ANON_KEY");
  if (!token || !url || !key) {
    return { error: errorResult("MCP runtime is missing required backend configuration.") };
  }
  return {
    client: createClient(url, key, {
      global: { headers: { Authorization: `Bearer ${token}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    })
  };
};

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's public SpotVault profile fields and OAuth email address.",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (_args, ctx) => {
    const userId = ctx.getUserId();
    const { client, error } = supabaseForUser(ctx);
    if (error) return error;
    if (!userId) return { content: [{ type: "text", text: "Could not identify the signed-in user." }], isError: true };
    const { data, error: queryError } = await client.from("profiles_public").select("id,display_name,avatar_url,bio,phone,created_at").eq("id", userId).maybeSingle();
    if (queryError) return { content: [{ type: "text", text: queryError.message }], isError: true };
    const profile = { ...data ?? { id: userId }, email: ctx.getUserEmail() ?? null };
    return textResult("Profile loaded.", { profile });
  }
});

// src/lib/mcp/tools/list-my-bookings.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var list_my_bookings_default = defineTool2({
  name: "list_my_bookings",
  title: "List my bookings",
  description: "List the signed-in user's SpotVault bookings without exposing payment tokens, IDs, or private vehicle/license details.",
  inputSchema: {
    status: z.string().optional().describe("Optional booking status filter."),
    limit: z.number().optional().describe("Maximum number of bookings to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ status, limit }, ctx) => {
    const userId = ctx.getUserId();
    const { client, error } = supabaseForUser(ctx);
    if (error) return error;
    if (!userId) return { content: [{ type: "text", text: "Could not identify the signed-in user." }], isError: true };
    let query = client.from("bookings").select("id,listing_id,seeker_id,provider_id,status,escrow_status,start_date,end_date,total_amount,category,city,created_at,listings(title,city,province,type,category)").or(`seeker_id.eq.${userId},provider_id.eq.${userId}`).order("created_at", { ascending: false }).limit(clampLimit(limit, 10, 25));
    if (status?.trim()) query = query.eq("status", status.trim());
    const { data, error: queryError } = await query;
    if (queryError) return { content: [{ type: "text", text: queryError.message }], isError: true };
    const bookings = (data ?? []).map((booking) => ({
      id: booking.id,
      listing_id: booking.listing_id,
      role: booking.seeker_id === userId ? "seeker" : "provider",
      status: booking.status,
      escrow_status: booking.escrow_status,
      start_date: booking.start_date,
      end_date: booking.end_date,
      total_amount: booking.total_amount,
      category: booking.category,
      city: booking.city,
      created_at: booking.created_at,
      listing: booking.listings
    }));
    return textResult(
      bookings.length ? `Found ${bookings.length} booking${bookings.length === 1 ? "" : "s"}.` : "No bookings found for this account.",
      { bookings }
    );
  }
});

// src/lib/mcp/tools/list-my-listings.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_my_listings_default = defineTool3({
  name: "list_my_listings",
  title: "List my listings",
  description: "List parking and storage listings owned by the signed-in SpotVault user, including approval and activity status.",
  inputSchema: {
    status: z2.string().optional().describe("Optional listing status filter."),
    limit: z2.number().optional().describe("Maximum number of listings to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ status, limit }, ctx) => {
    const userId = ctx.getUserId();
    const { client, error } = supabaseForUser(ctx);
    if (error) return error;
    if (!userId) return { content: [{ type: "text", text: "Could not identify the signed-in user." }], isError: true };
    let query = client.from("listings").select("id,title,type,category,city,province,region,status,is_active,is_approved,price_hourly,price_daily,price_weekly,price_monthly,availability,instant_book,avg_rating,created_at,updated_at").or(`user_id.eq.${userId},host_id.eq.${userId}`).order("updated_at", { ascending: false }).limit(clampLimit(limit, 10, 25));
    if (status?.trim()) query = query.eq("status", status.trim());
    const { data, error: queryError } = await query;
    if (queryError) return { content: [{ type: "text", text: queryError.message }], isError: true };
    const listings = data ?? [];
    return textResult(
      listings.length ? `Found ${listings.length} listing${listings.length === 1 ? "" : "s"} owned by this account.` : "No listings found for this account.",
      { listings }
    );
  }
});

// src/lib/mcp/tools/search-approved-listings.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
var search_approved_listings_default = defineTool4({
  name: "search_approved_listings",
  title: "Search approved listings",
  description: "Search public, approved SpotVault parking and storage listings by city, type, category, and price.",
  inputSchema: {
    city: z3.string().optional().describe("City name to match, such as Montreal or Quebec City."),
    type: z3.enum(["parking", "storage"]).optional().describe("Listing type to return."),
    category: z3.string().optional().describe("Listing category to match."),
    max_price: z3.number().optional().describe("Maximum matching hourly, daily, weekly, or monthly price."),
    limit: z3.number().optional().describe("Maximum number of listings to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ city, type, category, max_price, limit }, ctx) => {
    const { client, error } = supabaseForUser(ctx);
    if (error) return error;
    const itemLimit = clampLimit(limit, 10, 20);
    let query = client.from("listings").select("id,title,type,category,city,province,region,price_hourly,price_daily,price_weekly,price_monthly,availability,instant_book,avg_rating,size,size_sqft,spots,created_at").eq("is_approved", true).eq("is_active", true).order("created_at", { ascending: false }).limit(itemLimit);
    if (city?.trim()) query = query.ilike("city", `%${city.trim()}%`);
    if (type) query = query.eq("type", type);
    if (category?.trim()) query = query.ilike("category", `%${category.trim()}%`);
    if (typeof max_price === "number" && Number.isFinite(max_price)) {
      const price = Math.max(0, max_price);
      query = query.or(`price_hourly.lte.${price},price_daily.lte.${price},price_weekly.lte.${price},price_monthly.lte.${price}`);
    }
    const { data, error: queryError } = await query;
    if (queryError) return { content: [{ type: "text", text: queryError.message }], isError: true };
    const listings = data ?? [];
    return textResult(
      listings.length ? `Found ${listings.length} approved listing${listings.length === 1 ? "" : "s"}.` : "No approved listings matched this search.",
      { listings }
    );
  }
});

// src/lib/mcp/index.ts
var projectRef = "skfaqjatbqrmfkojtqsz";
var mcp_default = defineMcp({
  name: "spotvault-mcp",
  title: "SpotVault MCP",
  version: "0.1.0",
  instructions: "Tools for SpotVault, a Quebec parking and storage marketplace. Use these tools only after the user has connected with OAuth. RLS and app policies decide which rows the signed-in user can access.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    search_approved_listings_default,
    list_my_listings_default,
    list_my_bookings_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
